# Generated by Django 5.2.3 on 2025-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0002_alter_cardiac_arrest_prediction_fid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister_model',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
